##Numpy array and basics

In [3]:
import numpy as np

creating array from list

In [6]:
arr_1d = np.array([2,34,421,223,])
print("1D array:", arr_1d)

arr_2d = np.array([[12,1,23],[21,2,21]])
print("2D array:", arr_2d)

1D array: [  2  34 421 223]
2D array: [[12  1 23]
 [21  2 21]]


### List vs numpy array

In [3]:
import numpy as np
import time

py_list = [1,2,3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(100000)]
print("\nList operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\nNumpy operation time: ", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

List operation time:  0.013972043991088867

Numpy operation time:  0.002983570098876953


creating array from scratch

In [8]:
zeros = np.zeros((3,4))
print("zero array: \n", zeros)

ones = np.ones((2,3))
print("one array: \n", ones)

full = np.full((2,2), 7)
print("one array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 10, 3)
print("sequence array: \n", sequence)

zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
one array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.53655269 0.61504089 0.46424427]
 [0.05844454 0.11249544 0.138627  ]]
sequence array: 
 [0 3 6 9]


Vector, Matrix and Tensor

In [14]:
vector = np.array([1,23,21,2])
print("Vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector:  [ 1 23 21  2]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [17]:
arr = np.array([[1,2,3],[4,5,"6.8"]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Dtype ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  <U21


Array shipping

In [22]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n reveld array ", raveled)

# transpose
transpose = reshaped.T
print("\n Transpose array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveld array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
